#!/bin/zsh

local cmd
if command -v fd >/dev/null 2>&1; then
  cmd="command fd --type directory --follow --hidden --no-ignore-vcs . 2> /dev/null"
else
  cmd="command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' \
    -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) \
    -prune -o -type d -print 2> /dev/null | cut -b3-"
fi

setopt localoptions pipefail 2> /dev/null
local dir="$(eval "$cmd" | $(__fzf_cmd) "$FZF_DEFAULT_OPTS" +m --reverse)"
if [[ -z "$dir" ]]; then
  zle redisplay
  return 0
fi
cd "$dir"
local ret=$?

local precmd
for precmd in $precmd_functions; do
  $precmd
done
zle reset-prompt
typeset -f zle-line-init >/dev/null && zle zle-line-init
return $ret
